#!/usr/bin/env python3
"""
git/auto_commit.py — CLI wrapper for autonomous git commit
==========================================================
Sovereign Suite — Git Automation

Invoked by /execute-build Step 6b (phase-boundary sealing) and
/implementation-plan --audit pre-check (Coverage Ledger boundary cleanup).

Usage:
    python3 ~/blueprint-workflows/scripts/git/auto_commit.py \
        --workspace /abs/path/to/workspace \
        --message "phase-38: magnitude-aware formatter [proforma]" \
        --output-json

Output (--output-json):
    {
      "success": true,
      "short_hash": "a1b2c3d",
      "message": "phase-38: ...",
      "files_summary": "3 files changed, 42 insertions(+), 5 deletions(-)",
      "note": null,
      "reason": null
    }

    note == "nothing-to-commit"  → workspace already clean; not an error.
    success == false             → real failure; see "reason" field.
"""

import sys
import json
import argparse
from pathlib import Path

# Resolve the scripts/ directory so core.git_ops is importable regardless of cwd
_SCRIPTS_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_SCRIPTS_DIR))

from core.git_ops import auto_commit  # noqa: E402


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Autonomously stage and commit all workspace changes.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--workspace",
        required=True,
        help="Absolute path to the git workspace root.",
    )
    parser.add_argument(
        "--message",
        required=True,
        help="Commit message. Generated by the LLM agent at the call site.",
    )
    parser.add_argument(
        "--output-json",
        action="store_true",
        help="Print result as JSON (default: human-readable one-liner).",
    )
    args = parser.parse_args()

    workspace = Path(args.workspace)
    if not workspace.is_absolute():
        print(f"[auto_commit] ERROR: --workspace must be an absolute path (got: {args.workspace})",
              file=sys.stderr)
        sys.exit(1)

    result = auto_commit(workspace, args.message)

    if args.output_json:
        print(json.dumps(result, indent=2))
        return

    # Human-readable summary
    if result["success"] and result["short_hash"]:
        print(f"[auto_commit] COMMITTED {result['short_hash']} — {result['message']}")
        if result.get("files_summary"):
            for line in result["files_summary"].splitlines()[-3:]:
                print(f"  {line}")
    elif result.get("note") == "nothing-to-commit":
        print("[auto_commit] NOTHING TO COMMIT — phase boundary already clean.")
    else:
        print(f"[auto_commit] FAILED: {result.get('reason', 'unknown error')}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
