#!/usr/bin/env python3
"""
registry.py — Suite Learning Registry CLI
==========================================
Aggregates per-workspace `.history/*.ledger.md` ledgers + the `helpdesk-tickets/`
corpus into a central `manifest/CONTRADICTION_REGISTRY.md`, and computes a
reviewed-watermark delta. Default: writes/updates the registry. Use --report-only
to aggregate without writing.

The registry file uses TWO retention contracts (dogfooding /nodelete):
  * a SNAPSHOT block (between markers) — regenerated each run (Live-State / clean replace)
  * an Event Log — append-only (new events appended at EOF, deduped by ref)

A `REVIEW` verdict is a PROMPT for the LLM, not a decision. The engine never files
tickets and never judges significance — it counts.

Usage:
    python registry.py --workspace /abs/path [--threshold N] [--report-only]
                       [--output-json] [--quiet]

Hook: called by /harden-workflow --tickets (a frequent, architect-run invocation).

Origin: helpdesk ticket 20260612_contradiction-registry_engine.md.
"""

import argparse
import re
import sys
from datetime import date, datetime, timezone
from pathlib import Path

_HERE = Path(__file__).resolve().parent
if str(_HERE.parent) not in sys.path:
    sys.path.insert(0, str(_HERE.parent))

from engine_utils import safe_read
from registry.aggregator import aggregate, collect_events
from registry.reporter import RegistryReporter
from registry import __version__  # resolves to the package, now loaded via the dotted imports above

SCHEMA_VERSION = "1.0"
DEFAULT_THRESHOLD = 10
REGISTRY_RELPATH = "manifest/CONTRADICTION_REGISTRY.md"
SNAPSHOT_START = "<!-- REGISTRY-SNAPSHOT-START -->"
SNAPSHOT_END = "<!-- REGISTRY-SNAPSHOT-END -->"
LOG_HEADER = "## Event Log (append-only)"
_REVIEWED_RE = re.compile(r"\[REVIEWED\s+(\d{4}-\d{2}-\d{2})\]")
_ADVISORY = (
    "registry.py aggregates and counts deterministically; it does NOT judge whether "
    "a pattern is significant. verdict=REVIEW is a prompt for the LLM to ingest the "
    "aggregate and file a /helpdesk-tickets entry only if a real recurring pattern is "
    "found. The script never files tickets."
)
_HEADER = (
    "# CONTRADICTION_REGISTRY.md — Suite Learning Aggregate\n"
    "<!-- Generated by scripts/registry/registry.py. The SNAPSHOT block is regenerated\n"
    "     each run (Live-State). The Event Log is append-only. To mark events reviewed,\n"
    "     append a line:  [REVIEWED YYYY-MM-DD]  -->"
)


class RegistryEngine:
    def __init__(self, workspace, threshold=DEFAULT_THRESHOLD, apply=True):
        self.workspace = Path(workspace).resolve()
        self.threshold = int(threshold)
        self.apply = apply
        self.registry_path = self.workspace / REGISTRY_RELPATH

    def run(self) -> dict:
        events = collect_events(self.workspace)
        agg = aggregate(events)
        existing = safe_read(self.registry_path) if self.registry_path.exists() else ""
        known_refs = self._existing_refs(existing)
        watermark = self._last_reviewed(existing)
        new_events = [e for e in events if e.ref not in known_refs]
        unreviewed = sum(1 for e in events if e.date and (not watermark or e.date > watermark))
        verdict = "REVIEW" if unreviewed >= self.threshold else "NONE"

        wrote = False
        if self.apply:
            wrote = self._write_registry(events, agg, new_events, watermark, unreviewed, verdict)

        return {
            "schema_version": SCHEMA_VERSION,
            "tool": "registry",
            "tool_version": __version__,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "workspace": str(self.workspace),
            "registry_path": str(self.registry_path),
            "aggregate": agg,
            "new_events": len(new_events),
            "unreviewed": unreviewed,
            "watermark": watermark,
            "threshold": self.threshold,
            "verdict": verdict,
            "wrote": wrote,
            "summary": {"advisory": _ADVISORY},
        }

    # --- registry-file management ---------------------------------------

    @staticmethod
    def _existing_refs(text):
        refs = set()
        for line in text.splitlines():
            if line.startswith("- "):
                parts = [p.strip() for p in line[2:].split(" | ")]
                if len(parts) >= 3:
                    refs.add(parts[2])
        return refs

    @staticmethod
    def _last_reviewed(text):
        dates = _REVIEWED_RE.findall(text)
        return max(dates) if dates else ""

    @staticmethod
    def _event_line(e):
        pats = ",".join(e.patterns) if e.patterns else "-"
        return f"- {e.date or '?'} | {e.source} | {e.ref} | patterns={pats} | {e.workflow or '-'}"

    def _render_snapshot(self, agg, watermark, unreviewed, verdict):
        today = date.today().isoformat()
        pat = ", ".join(f"{k}: {v}" for k, v in agg["by_pattern"].items()) or "none"
        wf = ", ".join(f"{k}: {v}" for k, v in list(agg["by_workflow"].items())[:10]) or "none"
        src = ", ".join(f"{k}: {v}" for k, v in agg["by_source"].items()) or "none"
        return "\n".join([
            f"## Snapshot — regenerated {today}",
            f"- Total events: {agg['total_events']}",
            f"- Unreviewed since {watermark or '(never reviewed)'}: {unreviewed}  →  "
            f"verdict: {verdict} (threshold {self.threshold})",
            f"- By failure pattern: {pat}",
            f"- By workflow/target: {wf}",
            f"- By source: {src}",
        ])

    @staticmethod
    def _replace_block(content, start, end, body):
        s = content.find(start)
        e = content.find(end)
        if s == -1 or e == -1 or e < s:
            return content  # markers missing/corrupt — never mangle the file
        return content[:s + len(start)] + "\n" + body + "\n" + content[e:]

    def _write_registry(self, events, agg, new_events, watermark, unreviewed, verdict):
        self.registry_path.parent.mkdir(parents=True, exist_ok=True)
        existing = safe_read(self.registry_path) if self.registry_path.exists() else ""
        snapshot = self._render_snapshot(agg, watermark, unreviewed, verdict)

        if not existing.strip():
            log_lines = [self._event_line(e)
                         for e in sorted(events, key=lambda x: (x.date, x.ref))]
            content = (
                _HEADER + "\n\n"
                + SNAPSHOT_START + "\n" + snapshot + "\n" + SNAPSHOT_END + "\n\n"
                + LOG_HEADER + "\n" + ("\n".join(log_lines) + "\n" if log_lines else "")
            )
        else:
            content = self._replace_block(existing, SNAPSHOT_START, SNAPSHOT_END, snapshot)
            if new_events:
                add = "\n".join(self._event_line(e)
                                for e in sorted(new_events, key=lambda x: (x.date, x.ref)))
                content = content.rstrip("\n") + "\n" + add + "\n"

        self.registry_path.write_text(content, encoding="utf-8")
        return True


def _parse_args():
    p = argparse.ArgumentParser(
        prog="registry.py",
        description="Suite Learning Registry — aggregates .history ledgers + tickets "
                    "into manifest/CONTRADICTION_REGISTRY.md and computes a review delta.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--workspace", required=True, type=str,
                   help="Absolute path to the workspace root to aggregate.")
    p.add_argument("--threshold", type=int, default=DEFAULT_THRESHOLD,
                   help=f"Unreviewed-event count that triggers REVIEW (default {DEFAULT_THRESHOLD}).")
    p.add_argument("--report-only", action="store_true",
                   help="Aggregate and report without writing the registry file.")
    p.add_argument("--output-json", action="store_true", help="Emit JSON to stdout.")
    p.add_argument("--quiet", action="store_true", help="Suppress human-readable output.")
    return p.parse_args()


def main():
    args = _parse_args()
    workspace = Path(args.workspace).resolve()
    if not workspace.is_dir():
        print(f"[ERROR] Workspace is not a directory: {workspace}", file=sys.stderr)
        return 1
    report = RegistryEngine(workspace, threshold=args.threshold,
                            apply=not args.report_only).run()
    RegistryReporter().render(report, quiet=args.quiet, output_json=args.output_json)
    # Exit 0 always: REVIEW is advisory, not an error.
    return 0


if __name__ == "__main__":
    sys.exit(main())
